

const skills = [
    "Web Development",
    "Mobile App Development",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Cloud Computing",
    "DevOps",
    "UI/UX Design",
    "Product Management",
    "Cybersecurity",
    "Blockchain",
    "Game Development",
    "Software Testing",
    "Embedded Systems",
    "IoT",
    "AR/VR Development",
    "Big Data",
    "Business Analysis",
    "Technical Writing",
    "Graphic Design",
    "Video Editing",
    "Content Creation",
    "SEO",
    "Digital Marketing",
    "Social Media Management",
    "E-commerce",
    "Networking",
    "System Administration",
    "Data Engineering",
    "Database Management",
    "Quality Assurance",
    "Robotics",
    "Open Source",
    "Freelancing",
    "Entrepreneurship",
    "Leadership",
    "Public Speaking",
    "Mentorship",
    "Teaching",
    "Research",
    "Hardware Engineering"
]

export default skills;